"""Initial database schema

Revision ID: b2b9e0e2d060
Revises: 
Create Date: 2026-01-29 02:25:10.190353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b9e0e2d060'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('bank_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_norm', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UNRECONCILED', 'MATCHED', 'EXCEPTION', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bank_txn_match', 'bank_transactions', ['currency', 'amount', 'bank_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_account_id'), 'bank_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_amount'), 'bank_transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_bank_transactions_bank_date'), 'bank_transactions', ['bank_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_currency'), 'bank_transactions', ['currency'], unique=False)
    op.create_index(op.f('ix_bank_transactions_import_batch_id'), 'bank_transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_reference'), 'bank_transactions', ['reference'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.Column('book_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UNRECONCILED', 'MATCHED', 'EXCEPTION', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_txn_match', 'ledger_transactions', ['currency', 'amount', 'book_date'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_amount'), 'ledger_transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_book_date'), 'ledger_transactions', ['book_date'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_company_id'), 'ledger_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_currency'), 'ledger_transactions', ['currency'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_doc_id'), 'ledger_transactions', ['doc_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_reference'), 'ledger_transactions', ['reference'], unique=False)
    op.create_table('reconciliation_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_audit_timestamp'), 'reconciliation_audit', ['timestamp'], unique=False)
    op.create_table('reconciliation_match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bank_txn_id', sa.String(), nullable=False),
    sa.Column('ledger_txn_id', sa.String(), nullable=False),
    sa.Column('match_type', sa.Enum('RULE1', 'RULE2', 'RULE3', 'RULE4', 'SPLIT', 'MERGE', 'MANUAL', name='matchtype'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('AUTO', 'MANUAL', 'REJECTED', name='decisiontype'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bank_txn_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['ledger_txn_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_match')
    op.drop_index(op.f('ix_reconciliation_audit_timestamp'), table_name='reconciliation_audit')
    op.drop_table('reconciliation_audit')
    op.drop_index(op.f('ix_ledger_transactions_reference'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_doc_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_currency'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_company_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_book_date'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_amount'), table_name='ledger_transactions')
    op.drop_index('idx_ledger_txn_match', table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_bank_transactions_reference'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_import_batch_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_currency'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_amount'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_account_id'), table_name='bank_transactions')
    op.drop_index('idx_bank_txn_match', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
