"""
Settings API for AI configuration
"""
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from app.core.config import settings
from app.api.deps import get_current_user, require_company_owner
from app.models.identity import User
from datetime import datetime
import os
import logging
import re
import shutil

logger = logging.getLogger(__name__)

router = APIRouter()


class AISettingsRequest(BaseModel):
    ai_enhance_api_key: str
    ai_enhance_use_reasoner: bool = False
    ai_enhance_api_base: str = ""


class EnvSetting(BaseModel):
    key: str
    value: str


class EnvSettingsRequest(BaseModel):
    settings: list[EnvSetting]
    delete_keys: list[str] = []


class GatewayFields(BaseModel):
    api_url: str | None = None
    model: str | None = None
    api_key: str | None = None


class ApiSettingsPutRequest(BaseModel):
    gateways: dict[str, GatewayFields] = Field(default_factory=dict)


class ApiSettingsTestRequest(BaseModel):
    gateway: str
    api_url: str | None = None
    model: str | None = None
    api_key: str | None = None


_ENV_KEY = re.compile(r"^[A-Z][A-Z0-9_]*$")
_SECRET_HINTS = ("KEY", "TOKEN", "SECRET", "PASSWORD", "HASH", "INVITE")
_SECRET_KEY_EXACT = frozenset({
    "DATABASE_URL",
    "REDIS_URL",
    "REGISTER_INVITE_CODE",
    "CORS_ORIGINS",
})
# SEC-CODE-012: process-wide keys a workspace owner must not rewrite via Settings.
_PROTECTED_ENV_KEYS = frozenset({
    "JWT_SECRET_KEY",
    "DATABASE_URL",
    "DATABASE_PASSWORD",
    "SQLITE_KEY",
    "REGISTER_INVITE_CODE",
    "CORS_ORIGINS",
    "ALLOW_LEGACY_HEADER_AUTH",
    "ALLOW_INSECURE_DEV_JWT",
    "HOST",
    "TRUST_FORWARDED_HEADERS",
    "REDIS_URL",
})


def _env_path() -> str:
    backend_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
    path = os.path.join(backend_dir, ".env")
    if os.path.exists(path):
        return path
    return os.path.join(os.path.dirname(backend_dir), ".env")


def _read_env_file(path: str) -> dict[str, str]:
    env_vars: dict[str, str] = {}
    if not os.path.exists(path):
        return env_vars
    with open(path, "r", encoding="utf-8") as handle:
        for raw in handle:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            env_vars[key.strip()] = value.strip().strip('"')
    return env_vars


def _backup_env(path: str) -> str | None:
    if not os.path.exists(path):
        return None
    backup = f"{path}.{datetime.utcnow().strftime('%Y%m%d%H%M%S')}.bak"
    shutil.copy2(path, backup)
    return backup


def _write_env_file(path: str, env_vars: dict[str, str]) -> str | None:
    backup = _backup_env(path)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("# Local app configuration\n")
        handle.write("# Auto-generated by Settings API. Restart backend after changes.\n\n")
        for key in sorted(env_vars):
            value = env_vars[key]
            if " " in value or "#" in value:
                value = f'"{value}"'
            handle.write(f"{key}={value}\n")
    return backup


def _validate_env_key(key: str) -> str:
    value = (key or "").strip().upper()
    if not _ENV_KEY.match(value):
        raise ValueError(f"Invalid environment key: {key}")
    return value


def _is_secret_key(key: str) -> bool:
    upper = (key or "").upper()
    if upper in _SECRET_KEY_EXACT or upper in _PROTECTED_ENV_KEYS:
        return True
    if upper.endswith("_URL"):
        return True
    return any(hint in upper for hint in _SECRET_HINTS)


def _masked_value(key: str, value: str) -> str:
    if _is_secret_key(key):
        return "***" if value else ""
    return value


def _reject_protected_env_keys(keys: list[str]) -> None:
    blocked = sorted({(k or "").strip().upper() for k in keys} & _PROTECTED_ENV_KEYS)
    if blocked:
        raise HTTPException(
            status_code=403,
            detail=(
                "These settings cannot be changed from the app: "
                + ", ".join(blocked)
            ),
        )


@router.get("/settings/ai")
async def get_ai_settings(
    _user: User = Depends(get_current_user),
    _company_id: str = Depends(require_company_owner),
):
    """Get current AI settings (company owner)."""
    return {
        "ai_enhance_api_key": "***" if settings.ai_enhance_api_key else "",
        "ai_enhance_use_reasoner": settings.ai_enhance_use_reasoner,
        "ai_enhance_api_base": settings.ai_enhance_api_base,
        "ai_enhance_model": settings.ai_enhance_model,
        "has_api_key": bool(settings.ai_enhance_api_key),
    }


@router.post("/settings/ai")
async def update_ai_settings(
    request: AISettingsRequest,
    _user: User = Depends(get_current_user),
    _company_id: str = Depends(require_company_owner),
):
    """
    Update AI settings

    Note: This updates the .env file. The backend needs to be restarted
    for changes to take effect (or use environment variable reload).
    """
    try:
        env_path = _env_path()
        env_vars = _read_env_file(env_path)

        if request.ai_enhance_api_key and request.ai_enhance_api_key != "***":
            env_vars["AI_ENHANCE_API_KEY"] = request.ai_enhance_api_key
        elif "AI_ENHANCE_API_KEY" not in env_vars:
            env_vars["AI_ENHANCE_API_KEY"] = request.ai_enhance_api_key

        env_vars["AI_ENHANCE_USE_REASONER"] = (
            "true" if request.ai_enhance_use_reasoner else "false"
        )
        env_vars["AI_ENHANCE_BASE_URL"] = request.ai_enhance_api_base

        backup = _write_env_file(env_path, env_vars)

        logger.info(
            "Updated AI settings: use_reasoner=%s, api_base=%s",
            request.ai_enhance_use_reasoner,
            request.ai_enhance_api_base,
        )

        return {
            "success": True,
            "message": "Settings saved. Please restart the backend for changes to take effect.",
            "backup_path": backup,
            "settings": {
                "ai_enhance_use_reasoner": request.ai_enhance_use_reasoner,
                "ai_enhance_api_base": request.ai_enhance_api_base,
                "has_api_key": bool(request.ai_enhance_api_key),
            },
        }
    except Exception as e:
        logger.error(f"Failed to update settings: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to save settings: {str(e)}",
        )


@router.get("/settings/env")
async def get_env_settings(
    _user: User = Depends(get_current_user),
    _company_id: str = Depends(require_company_owner),
):
    path = _env_path()
    env_vars = _read_env_file(path)
    return {
        "env_path": os.path.basename(path) or ".env",
        "restart_required": True,
        "settings": [
            {
                "key": key,
                "value": _masked_value(key, value),
                "is_secret": _is_secret_key(key) and bool(value),
            }
            for key, value in sorted(env_vars.items())
        ],
    }


@router.post("/settings/env")
async def update_env_settings(
    request: EnvSettingsRequest,
    _user: User = Depends(get_current_user),
    _company_id: str = Depends(require_company_owner),
):
    try:
        path = _env_path()
        env_vars = _read_env_file(path)
        _reject_protected_env_keys(
            [_validate_env_key(k) for k in request.delete_keys]
            + [_validate_env_key(item.key) for item in request.settings]
        )
        for key in request.delete_keys:
            env_vars.pop(_validate_env_key(key), None)
        for item in request.settings:
            key = _validate_env_key(item.key)
            if item.value == "***" and key in env_vars:
                continue
            env_vars[key] = item.value
        backup = _write_env_file(path, env_vars)
        return {
            "success": True,
            "message": "Settings saved. Please restart the backend for changes to take effect.",
            "backup_path": backup,
            "restart_required": True,
        }
    except HTTPException:
        raise
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:
        logger.error("Failed to update env settings: %s", exc, exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to save settings: {str(exc)}") from exc


@router.get("/settings/api")
async def get_api_settings(
    _user: User = Depends(get_current_user),
    _company_id: str = Depends(require_company_owner),
):
    """Return five shared gateways: stored (masked) + effective resolved preview."""
    from app.core.gateway_settings import (
        GATEWAY_IDS,
        mask_gateway,
        resolve_gateway,
        stored_gateway,
    )

    gateways = {gid: mask_gateway(stored_gateway(gid)) for gid in GATEWAY_IDS}
    effective = {gid: mask_gateway(resolve_gateway(gid)) for gid in GATEWAY_IDS}
    return {
        "gateways": gateways,
        "effective": effective,
        "restart_required": False,
    }


@router.put("/settings/api")
async def put_api_settings(
    request: ApiSettingsPutRequest,
    _user: User = Depends(get_current_user),
    _company_id: str = Depends(require_company_owner),
):
    """Apply gateway URL/model/key live (no restart). Ignores api_key of ***."""
    from app.core.gateway_settings import GATEWAY_IDS, apply_gateways

    if not request.gateways:
        raise HTTPException(status_code=400, detail="No gateways provided")

    updates: dict[str, dict[str, str | None]] = {}
    for gateway_id, fields in request.gateways.items():
        if gateway_id not in GATEWAY_IDS:
            raise HTTPException(status_code=400, detail=f"Unknown gateway: {gateway_id}")
        payload = fields.model_dump(exclude_unset=True)
        if payload:
            updates[gateway_id] = payload

    if not updates:
        raise HTTPException(status_code=400, detail="No gateway fields to update")

    try:
        result = apply_gateways(updates)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:
        logger.error("Failed to apply API settings: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=500, detail=f"Failed to save API settings: {exc}"
        ) from exc

    from app.core.gateway_settings import (
        GATEWAY_IDS as _IDS,
        mask_gateway,
        resolve_gateway,
        stored_gateway,
    )

    return {
        "success": True,
        "message": "API settings applied.",
        "restart_required": False,
        "backup_path": result.get("backup_path"),
        "gateways": {gid: mask_gateway(stored_gateway(gid)) for gid in _IDS},
        "effective": {gid: mask_gateway(resolve_gateway(gid)) for gid in _IDS},
    }


@router.post("/settings/api/test")
async def test_api_settings(
    request: ApiSettingsTestRequest,
    _user: User = Depends(get_current_user),
    _company_id: str = Depends(require_company_owner),
):
    """Probe an OpenAI-compatible gateway (body values or resolve fallbacks)."""
    from app.core.gateway_settings import GATEWAY_IDS, probe_gateway

    if request.gateway not in GATEWAY_IDS:
        raise HTTPException(status_code=400, detail=f"Unknown gateway: {request.gateway}")

    try:
        result = probe_gateway(
            gateway_id=request.gateway,
            api_url=request.api_url,
            model=request.model,
            api_key=request.api_key,
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return result
