"""
Central maximum sizes for user-controlled strings and JSON payloads.

Purpose: limit oversized requests (DoS, abuse). SQLAlchemy already binds parameters,
so these are not the primary SQL-injection control.
"""

# --- AI chat ---
MAX_AI_CHAT_SESSION_ID_CHARS = 400
MAX_AI_CHAT_MODE_CHARS = 32
MAX_AI_CHAT_MESSAGE_CHARS = 48_000
MAX_AI_CHAT_CONTEXT_JSON_BYTES = 3_000_000

MAX_AI_TITLE_MESSAGES = 24
MAX_AI_TITLE_MESSAGE_CONTENT_CHARS = 8_000

# --- Tasks / messages ---
MAX_TASK_TITLE_CHARS = 500
MAX_TASK_DUP_WARNING_CHARS = 20_000
MAX_TASK_MESSAGE_TEXT_CHARS = 500_000
MAX_TASK_MESSAGE_ROLE_CHARS = 32
MAX_TASK_MESSAGE_CONTENT_TYPE_CHARS = 40

# --- Markdown-scale bodies (profile, rule memory, company manual) ---
MAX_MARKDOWN_BODY_CHARS = 600_000

# --- Company profile form fields ---
MAX_COMPANY_NAME_CHARS = 500
MAX_PROFILE_SHORT_FIELD_CHARS = 2_000
MAX_COMPANY_KEYWORDS_COUNT = 80
MAX_COMPANY_KEYWORD_ITEM_CHARS = 200

# --- Rule memory ---
MAX_RULE_MEMORY_IMPORT_ITEMS = 40
MAX_RULE_MEMORY_GENERATE_DESCRIPTION_CHARS = 24_000

# --- Registration / identity ---
MAX_DISPLAY_NAME_CHARS = 120
MAX_USERNAME_CHARS = 64

# --- Company manual wizard ---
MAX_WIZARD_SHORT_FIELD_CHARS = 2_000
MAX_WIZARD_SECTION_CHARS = 120_000
MAX_BANK_FIELD_CHARS = 500

# --- Exclusion rules ---
MAX_EXCLUSION_PATTERN_CHARS = 4_000
MAX_EXCLUSION_REASON_CHARS = 4_000
MAX_EXCLUSION_MODES_CHARS = 256
MAX_EXCLUSION_TEST_SAMPLE_CHARS = 100_000
MAX_EXCLUSION_VENDOR_FIELD_CHARS = 2_000
